### ISSUE TITLE
Running on macOS results in failure

### ISSUE THREAD

**Issue by jadar** [ProfessorManhattan/ansible-androidstudio#4]
### ❔ What are you experiencing an issue with?

Latest Release

### ❔ Version

2.4.0

### 🐞 Description

When running this as a role with my playbook on macOS, I run into an error with Ansible. 

macOS: 15.0.1
Ansible: 2.15.12

### ⏺️ Steps To Reproduce

1. Add role to requirements.yml
2. Apply role in playbook. I did it through `include_role`
3. Run the playbook with `--ask-become-pass`

```yaml
---
- hosts: localhost
  tasks:
    - name: Install Android Studio
      include_role:
        name: professormanhattan.androidstudio
```

### 📒 Relevant Log Output

```shell
TASK [professormanhattan.androidstudio : Ensure custom facts directory exists] ********************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: Invalid file mode: A+user:{{ ansible_user if ansible_os_family == 'Windows' else omit }}:rx:allow\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.15/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user#risks-of-becoming-an-unprivileged-user"}
```
